services:
  app-health-service:
    build:
      context: ..
      dockerfile: deploy-service/Dockerfile
    image: app-health-service:local
    container_name: app-health-service-local
    env_file:
      - ./.env
    ports:
      - '${APP_HEALTH_SERVICE_PORT:-8080}:8080'
    restart: unless-stopped
